#!/bin/sh
gfortran -o blh2xyz blh2xyz_ori.for
gfortran -o dcor dcor.f90
gfortran -o dem dem.f90
gfortran -o demcor demcor.f90
gfortran -o gfig gfig.f90
gfortran -o h h.f90
gfortran -o model model.f90
gfortran -o obs obs.f90
gfortran -o obscentre obscentre.f90
gfortran -o topo topo.f90
gfortran -o calx x.f90
gfortran -o caly y.f90
gfortran -o calxy xy.f90
gfortran -o seadem seadem.f90
gfortran -o seah seah.f90
gfortran -o seastart seastart.f90
gfortran -o range range.f90
gfortran -o mesh mesh.f90
gfortran -o p2p p2p.f90
